apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: http
      port: 9000
      targetPort: http
