apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: database
resources:
  - sts.yml
  - service.yml
secretGenerator:
  - name: couchdb-user
    literals:
      - COUCHDB_USER=enseada
      - COUCHDB_PASSWORD=enseada
