apiVersion: v1
kind: Service
metadata:
  name: couchdb
spec:
  selector:
    app.kubernetes.io/name: couchdb
  type: ClusterIP
  ports:
    - name: http
      port: 5984
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: http
