[package]
name = "maven_version"
version = "0.1.0"
authors = ["Matteo Joliveau <matteojoliveau@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "^1.0", optional = true }

[dev-dependencies]
rstest = "0.6.4"
