name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - uses: actions/checkout@v1
      - name: Login to Quay
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin quay.io
      - name: Build the Docker image
        run: |
         [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,' | sed -e 's/^v//')
          # Strip "v" prefix from tag name
          docker pull quay.io/enseada/enseada:latest || true
          docker build --file Dockerfile --tag enseada/enseada:$VERSION --tag quay.io/enseada/enseada:latest --cache-from quay.io/enseada/enseada:latest .
          docker push quay.io/enseada/enseada:$VERSION
          docker push quay.io/enseada/enseada:latest